version: '3.8'

services:

  db:
    image: postgres:15-alpine
    container_name: db_transito
    environment:
      POSTGRES_USER: admin_transito
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: transito_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/src/database/schema.sql:/docker-entrypoint-initdb.d/init.sql
  
  app:
    build: ./backend
    container_name: app_transito
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=admin_transito
      - DB_PASSWORD=password123
      - DB_NAME=transito_db
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  postgres_data: